platform :ios, '13.0'

def capacitor_pods
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Capacitor', :path => '../node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../node_modules/@capacitor/ios'
end

def couchbase_pods
  use_frameworks!
  pod 'CouchbaseLite-Swift-Enterprise', '~> 3.2'
end

target 'Plugin' do
  couchbase_pods
  capacitor_pods
end

target 'PluginTests' do
  couchbase_pods
  capacitor_pods
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
    end
  end
end
